### ISSUE TITLE
Integrate to AppVeyor

### ISSUE THREAD

**Issue by pine613** [codecov/codecov-perl#12]
I want to integrate to AppVeyor this repository.
http://www.appveyor.com/

**Comment by pine613** [comment]
@stevepeak Best regards!

**Comment by stevepeak** [comment]
The AppVeyor CI variables are laid out here: https://github.com/cainus/codecov.io/blob/master/lib/services/appveyor.js

Thank you :)

**Comment by pine613** [comment]
Oh... Thanks.
But it does not seem to transmitted well.

I want to register AppVeyor this repository, and want to set WebHook URL on GitHub.
It is so good for developers to find a status badge of AppVeyor on README.md because codecov-perl supports AppVeyor. But, I don't have permission.

Best regards.

**Comment by stevepeak** [comment]
Added repo to AppVeyor: https://ci.appveyor.com/project/stevepeak/codecov-perl

Thank you!

**Comment by pine613** [comment]
Thank you :+1:
