### ISSUE TITLE
Add AppVeyor status badge to README.md

### ISSUE THREAD

**Issue by pine613** [codecov/codecov-perl#15]

**Comment by pine613** [comment]
@stevepeak Could you tell me image URL ?
![untitled](https://cloud.githubusercontent.com/assets/5249050/9289208/a6ffc594-43a2-11e5-91aa-29cbacf9cfa5.png)

**Comment by stevepeak** [comment]
[![Build status](https://ci.appveyor.com/api/projects/status/5lsn4kb9dt9fj9eq/branch/master?svg=true)](https://ci.appveyor.com/project/stevepeak/codecov-perl/branch/master)

Thank you :)

**Comment by pine613** [comment]
Thanks!
