### ISSUE TITLE
Uncoverable comments not taking into account

### ISSUE THREAD

**Issue by coolo** [codecov/codecov-perl#27]
```
    # uncoverable branch true
    open(my $fd, '<:raw:bytes', '/dev/urandom') || croak "can't open /dev/urandom: $!";
```

This is reported 100% covered when run under 'cover' - but uploaded as "1/2" when running under cover -report codecov

**Comment by pine** [comment]
I'm checking this PR 🤔 
https://github.com/os-autoinst/openQA/pull/1141
